source/hello/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]

source/webapp/urls.py
from django.urls import path


from webapp.views import add, subtract, multiply, divide, math_logic, get_token_view

app_name = 'webapp'

urlpatterns = [
    path('add/', add, name='add'),
    path('subtract/', subtract, name='subtract'),
    path('multiply/', multiply, name='multiply'),
    path('divide/', divide, name='divide'),
    path('', math_logic, name='math_logic'),
    path('csrftoken/', get_token_view, name='get_token_view')
]

source/webapp/models.py
from django.db import models

# Create your models here.

source/webapp/views.py
import json

from django.views.decorators.csrf import ensure_csrf_cookie
from django.http import HttpResponseNotAllowed, JsonResponse
from django.shortcuts import render

@ensure_csrf_cookie
def get_token_view(request, *args, **kwargs):
    if request.method == 'GET':
        return JsonResponse({})
    return HttpResponseNotAllowed('Only GET request are allowed')


def add(request):
    data = json.loads(request.body)
    try:
        total = int(data['num1']) + int(data['num2'])
        return JsonResponse({'answer': str(total), 'element' : '+'})
    except ValueError:
        return JsonResponse({'error': 'input only numbers'}, status=400)

def subtract(request):
    data = json.loads(request.body)
    try:
        total = int(data['num1']) - int(data['num2'])
        return JsonResponse({'answer': str(total), 'element' : '-'})
    except ValueError:
        return JsonResponse({'error': 'input only numbers'}, status=400)

def multiply(request):
    data = json.loads(request.body)
    try:
        total = int(data['num1']) * int(data['num2'])
        return JsonResponse({'answer': str(total), 'element' : '*'})
    except ValueError:
        return JsonResponse({'error': 'input only numbers'}, status=400)

def divide(request):
    data = json.loads(request.body)
    try:
        if int(data['num1']) == 0 or int(data['num2']) == 0:
            return JsonResponse({'error': 'division by zero!'}, status=400)
        else:
            total = int(data['num1']) / int(data['num2'])
            return JsonResponse({'answer': str(total), 'element' : '/'})
    except ValueError:
        return JsonResponse({'error': 'input only numbers'}, status=400)

def math_logic(request):
    return render(request, 'index.html')

source/webapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Title</title>
</head>
<body>
<div class="main-block">
    <div class="input"><input id="num1" type="text" placeholder="Number A"></div>
        <div class="buttons">
        <button id="btn" onclick="math(event)" data-math-url="{% url 'webapp:add' %}">add</button>
        <button id="btn" onclick="math(event)" data-math-url="{% url 'webapp:subtract' %}">subtract</button>
        <button id="btn" onclick="math(event)" data-math-url="{% url 'webapp:multiply' %}">multiply</button>
        <button id="btn" onclick="math(event)" data-math-url="{% url 'webapp:divide' %}">divide</button>
        </div>
    <div class="input"><input id="num2" type="text" placeholder="Number B"></div>
</div>
{#{% url 'webapp:add' %}#}

<script>
async function makeRequest(url, method) {
    let response = await fetch(url, method);
    if (response.ok) {
        return await response.json();
    } else {
        let error = new Error(response.statusText);
        error.response = response;
        err_response = await response.json()
        return err_response
    }
}

let math = async function (event){
    let url = event.target.dataset.mathUrl;
    let num1 = document.getElementById('num1').value;
    let num2 = document.getElementById('num2').value;
    let info = {
        'num1' : num1,
        'num2' : num2,
    };
    if (document.getElementById('answer')){
        block = document.getElementById('answer')
        block.remove()
    }
    let csrf = await makeRequest('http://localhost:8000/csrftoken/');
    let csrf_token = document.cookie.split('=')[1];
    let data = await makeRequest(url, {method: 'POST',
                                        body: JSON.stringify(info),
                                        headers: {
                                            'Content-Type': 'application/json',
                                            'X-CSRFToken': csrf_token}
                                        });
    let div = document.createElement('div');
    div.classList.add('answer');
    div.id = 'answer';
    let p = document.createElement('p');

    if (data['answer']){
        p.innerText = `${num1} ${data.element} ${num2} = ${data.answer}`;
        div.style.backgroundColor = 'green'
        p.style.color = 'white'
    }
    else{
        p.innerText = `${data.error}`;
        div.style.backgroundColor = 'red'
        p.style.color = 'white'
        p.style.fontSize = '25px'
    }
    div.appendChild(p)
    document.body.appendChild(div)
    let inputs = document.querySelectorAll('input[type=text]');
    for (let i = 0;  i < inputs.length; i++) {
    inputs[i].value = '';
    };
}
</script>
</body>
</html>